# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord', '~> 5'
gem 'sinatra', '~> 2.0.2'
gem 'sinatra-activerecord', '~> 2.0'

# If you want to use MySQL as backend database
#gem 'mysql2', '~> 0.4'

# If you want to use sqlite3 as database
gem 'sqlite3', '~> 1.3'

gem 'rake', '~> 12.0'

gem 'sinatra-swagger-exposer',
    git: 'https://github.com/NetcomKassel/sinatra-swagger-exposer.git'
